
### 配置信息获取API:
---
tags:
  - cmdb管理接口
parameters:
  - name: configEnv
    in: path
    type: string
    required: true
    enum: ['dev', 'prod']
    description: 配置环境
    default: "dev"
  - name: name
    in: query
    type: string
    required: true
    description: 应用名
    default: ""
  - name: limit
    in: query
    type: string
    description: 单页数量
    default: ""
  - name: offset
    in: query
    type: string
    description: 偏移量
    default: ""
responses:
  502:
    description: 发送消息失败回执
    schema:
      properties:
        code:
          type: string
          default: "502"
        msg:
          type: string
          default: ""
        status:
          type: string
          default: "error"
  200:
    description: 发送消息成功回执
    schema:
      properties:
        code:
          type: string
          default: "200"
        msg:
          type: string
          default: ""
        status:
          type: string
          default: "error"