
### 配置信息查询获取API:
---
tags:
  - cmdb管理接口
parameters:
  - name: configEnv
    in: path
    type: string
    required: true
    enum: ['dev', 'prod']
    description: 配置环境
    default: "dev"
  - name: type
    in: path
    type: string
    required: true
    enum: ['name', 'owner']
    description: 搜索方式
    default: "name"
  - name: data
    in: path
    type: string
    required: true
    description: 搜索内容
    default: ""
  - name: limit
    in: path
    type: string
    required: true
    description: 单页数量
    default: ""
  - name: offset
    in: path
    type: string
    required: true
    description: 偏移量
    default: ""
responses:
  502:
    description: 发送消息失败回执
    schema:
      properties:
        code:
          type: string
          default: "502"
        msg:
          type: string
          default: ""
        status:
          type: string
          default: "error"
  200:
    description: 发送消息成功回执
    schema:
      properties:
        code:
          type: string
          default: "200"
        msg:
          type: string
          default: ""
        status:
          type: string
          default: "error"